"""del pk game_id team_id stat_id from game_stat

Revision ID: 7cfda69bbb39
Revises: 5d8b70bdabb0
Create Date: 2025-04-28 19:17:40.896668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cfda69bbb39'
down_revision: Union[str, None] = '5d8b70bdabb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
