"""add fk coach_id to game

Revision ID: 10394d9f7d0b
Revises: 197c30f354e4
Create Date: 2025-04-29 02:00:57.121744

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10394d9f7d0b'
down_revision: Union[str, None] = '197c30f354e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('coach_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'game', 'coach', ['coach_id'], ['coach_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_column('game', 'coach_id')
    # ### end Alembic commands ###
