"""del table game_stat

Revision ID: 1a622c209677
Revises: 7527ba0b0a23
Create Date: 2025-04-28 19:45:09.175672

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a622c209677'
down_revision: Union[str, None] = '7527ba0b0a23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_stat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_stat',
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('stat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('min', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('plus_min', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('game_stat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], name='game_stat_game_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stat_id'], ['stat.stat_id'], name='game_stat_stat_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team.team_id'], name='game_stat_team_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('game_stat_id', name='game_stat_pkey')
    )
    # ### end Alembic commands ###
