"""add game_stat_id from game_stat

Revision ID: 5d8b70bdabb0
Revises: f690870224c7
Create Date: 2025-04-28 19:12:04.358156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d8b70bdabb0'
down_revision: Union[str, None] = 'f690870224c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_stat', sa.Column('game_stat_id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_stat', 'game_stat_id')
    # ### end Alembic commands ###
