"""update game_status_id autoincr false 

Revision ID: 81c5767e6ccd
Revises: fdceadb3592b
Create Date: 2025-04-28 00:54:13.841550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81c5767e6ccd'
down_revision: Union[str, None] = 'fdceadb3592b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_status', 'game_status_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False,
               autoincrement=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('game_status', 'game_status_id',
               existing_type=sa.INTEGER(),
               server_default=sa.text("nextval('game_status_game_status_id_seq'::regclass)"),
               existing_nullable=False,
               autoincrement=False)
    # ### end Alembic commands ###
