"""add fk left_right coach_id to game

Revision ID: 997dea4cb788
Revises: 10394d9f7d0b
Create Date: 2025-04-29 02:04:50.188999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '997dea4cb788'
down_revision: Union[str, None] = '10394d9f7d0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('left_coach_id', sa.String(), nullable=True))
    op.add_column('game', sa.Column('right_coach_id', sa.String(), nullable=True))
    op.drop_constraint('game_coach_id_fkey', 'game', type_='foreignkey')
    op.create_foreign_key(None, 'game', 'coach', ['right_coach_id'], ['coach_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'game', 'coach', ['left_coach_id'], ['coach_id'], ondelete='CASCADE')
    op.drop_column('game', 'coach_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('coach_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.create_foreign_key('game_coach_id_fkey', 'game', 'coach', ['coach_id'], ['coach_id'], ondelete='CASCADE')
    op.drop_column('game', 'right_coach_id')
    op.drop_column('game', 'left_coach_id')
    # ### end Alembic commands ###
