"""add game_stat_id

Revision ID: bd1225178ff2
Revises: dd0ed69883f8
Create Date: 2025-04-26 18:59:35.305056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd1225178ff2'
down_revision: Union[str, None] = 'dd0ed69883f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_stat', sa.Column('game_stat_id', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_stat', 'game_stat_id')
    # ### end Alembic commands ###
