"""add PredictionDrawLeftRight

Revision ID: e427dc538d45
Revises: 997dea4cb788
Create Date: 2025-05-12 01:05:47.923172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e427dc538d45'
down_revision: Union[str, None] = '997dea4cb788'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prediction_draw_left_right',
    sa.Column('prediction_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('min', sa.Integer(), nullable=True),
    sa.Column('plus_min', sa.Integer(), nullable=True),
    sa.Column('left_coach_id', sa.Integer(), nullable=False),
    sa.Column('right_coach_id', sa.Integer(), nullable=False),
    sa.Column('referee_id', sa.Integer(), nullable=False),
    sa.Column('left_num_v', sa.Integer(), nullable=False),
    sa.Column('left_num_z', sa.Integer(), nullable=False),
    sa.Column('left_num_p', sa.Integer(), nullable=False),
    sa.Column('left_num_n', sa.Integer(), nullable=False),
    sa.Column('left_num_u', sa.Integer(), nullable=False),
    sa.Column('right_num_v', sa.Integer(), nullable=False),
    sa.Column('right_num_z', sa.Integer(), nullable=False),
    sa.Column('right_num_p', sa.Integer(), nullable=False),
    sa.Column('right_num_n', sa.Integer(), nullable=False),
    sa.Column('right_num_u', sa.Integer(), nullable=False),
    sa.Column('left_num_y', sa.Integer(), nullable=False),
    sa.Column('left_num_y2r', sa.Integer(), nullable=False),
    sa.Column('right_num_y', sa.Integer(), nullable=False),
    sa.Column('right_num_y2r', sa.Integer(), nullable=False),
    sa.Column('right_num_goal_g', sa.Integer(), nullable=False),
    sa.Column('right_num_goal_p', sa.Integer(), nullable=False),
    sa.Column('right_num_goal_a', sa.Integer(), nullable=False),
    sa.Column('left_num_goal_g', sa.Integer(), nullable=False),
    sa.Column('left_num_goal_p', sa.Integer(), nullable=False),
    sa.Column('left_num_goal_a', sa.Integer(), nullable=False),
    sa.Column('left_total_transfer_value', sa.Float(), nullable=False),
    sa.Column('right_total_transfer_value', sa.Float(), nullable=False),
    sa.Column('left_avg_transfer_value', sa.Float(), nullable=False),
    sa.Column('right_avg_transfer_value', sa.Float(), nullable=False),
    sa.Column('left_goal_score', sa.Integer(), nullable=False),
    sa.Column('right_goal_score', sa.Integer(), nullable=False),
    sa.Column('left_avg_time_player_in_game', sa.Float(), nullable=False),
    sa.Column('right_avg_time_player_in_game', sa.Float(), nullable=False),
    sa.Column('left_right_transfer_value_div', sa.Float(), nullable=False),
    sa.Column('right_left_transfer_value_div', sa.Float(), nullable=False),
    sa.Column('res_event', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.game_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('prediction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prediction_draw_left_right')
    # ### end Alembic commands ###
