"""del game_stat_id from game_stat

Revision ID: f690870224c7
Revises: 81c5767e6ccd
Create Date: 2025-04-28 19:07:00.022327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f690870224c7'
down_revision: Union[str, None] = '81c5767e6ccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game_stat', 'game_stat_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game_stat', sa.Column('game_stat_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
